### ISSUE TITLE
KNN CUDA 

### ISSUE THREAD

**Issue by lixk28** [lixk28/knn-cuda#1]
# KNN CUDA

## Roadmap

After discussion, we decide to implement a few versions of KNN (using exhaustive search):
- [x] CPU version (ground truth for KNN)
- [x] CUDA version
  - [x] Distance matrix computing kernel.
  - [x] Sorting kernel.
- [x] CUBLAS + CUDA fused version
  - [x] Use CUBLAS library to accelerate the computation of distance matrix.

Apart from the missions listed above, several tasks also need to be finished:
- [x] Test cases (both some data set downloaded from Internet and randomly generated are OK)
- [x] Time measuring and collecting (make a few plots on different versions of KNN for comparsion, like running time and speedup)

### Coding Style
We basically follow the Linux kernel coding style.
- Snake case for variables, functions, function-like macros. Big case for macros.
- Opening brace at new line for functions, while for statements block, opening brace will be at the end of line. If there is only one statement in the block, no curly braces.
- Functions must have documenting comments, inline comments is welcome wherever necessary. 

### Commit Message
A commit message has the following format:
```
Title: Summarize changes in around 50 characters or less

Subtitle:
    - More detailed explanatory text, if necessary.
    - Explain the problem that this commit is solving. Or work you have done.

AnotherSubtitle:
   - Like todos.
```
 
## Building
release build:
```
make
```
debug build:
```
make BUILD=DEBUG
```
